# da dela na LANu
host: 192.168.6.29



###########
# site.url, site.title

title: 'Miro Maher, računalniške storitve'
author: 'Miro Maher'

markdown: kramdown
excerpt_separator: <!--more-->

sass:
  sass_dir: css
  style:    expanded

exclude:
- README.md


safe: true
lsi: false

